version: "3.8"

services:
  backend:
    build:
      context: ./backend # Path to the backend Dockerfile
    ports:
      - "8080:8080"

  backend2:
    build:
      context: ./backend # Path to the backend Dockerfile
    ports:
      - "8084:8080"

  auth-backend:
    build:
      context: ./auth-backend # Path to the backend Dockerfile
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend/client # Path to the frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend # Wait for backend service to be ready before starting frontend

  frontend2:
    build:
      context: ./frontend_2/client # Path to the frontend Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend # Wait for backend service to be ready before starting frontend
